ARG DATABASE_URL

FROM node:20.11-alpine as build 

###ARGS###
ARG NODE_TLS_REJECT_UNAUTHORIZED
ARG DATABASE_URL
ARG NITRO_HOST
ARG NITRO_PORT
ARG API_KEY
ARG API_UID
ARG API_GID
###ARGS###

WORKDIR /usr/src/app 

COPY package*.json ./ 

RUN npm install 

COPY . ./ 

RUN npx prisma generate
# RUN npx prisma db push

RUN npm run build 

######################################################

FROM node:20.11-alpine as prod 

###EXPOSING ARGS AS ENVS###
ARG NODE_TLS_REJECT_UNAUTHORIZED
ENV NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED}

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

ARG NITRO_HOST
ENV NITRO_HOST=${NITRO_HOST}

ARG NITRO_PORT
ENV NITRO_PORT=${NITRO_PORT}

ARG API_KEY
ENV API_KEY=${API_KEY}

ARG API_UID
ENV API_UID=${API_UID}

ARG API_GID
ENV API_GID=${API_GID}
###EXPOSING ARGS AS ENVS###

ENV NODE_ENV=production

EXPOSE 3000

WORKDIR /usr/src/app 

COPY nuxt.config.ts ./
COPY --from=build /usr/src/app/.nuxt ./.nuxt
COPY --from=build /usr/src/app/package*.json ./
COPY --from=build /usr/src/app/.output/ ./.output/ 
COPY --from=build /usr/src/app/prisma ./prisma 

CMD ["node", ".output/server/index.mjs"]

