version: '3'

services:

    mongo1:
        image: prismagraphql/mongo-single-replica:5.0.3
        hostname: mongo1
        volumes:
            - dbvolume:/var/lib/mongodb # assuming mongodb will store data
        expose:
            - 27017
        ports:
            - 3001:27017
        restart: always  
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGOD_INITDB_DATABASE: AiRQtest
            MONGO_REPLICA_HOST: mongo1
            MONGO_REPLICA_PORT: 27017 

    web:
        hostname: webapp
        build: 
            context: .
            dockerfile: ./Dockerfile_web
            args:
                - DATABASE_URL=mongodb://admin:password@mongo1:27017/AiRQtest?authSource=admin
                - NITRO_HOST='localhost'
                - NITRO_PORT='3000'
                - API_KEY="bd217a357d93379ac8e36d3d8c56af4d"
                - API_UID="solarlab"
                - API_GID="12003fb9"
        depends_on:
            - mongo1 
        expose: 
            - 3000
        ports:
            - 3000:3000
        
volumes:
    dbvolume:
