ARG DATABASE_URL

FROM node:20.11-alpine as build 

ARG DATABASE_URL

WORKDIR /usr/src/app 

COPY package*.json ./ 

RUN npm install 

COPY . ./ 

RUN npx prisma generate
# RUN npx prisma db push

RUN npm run build 

######################################################

FROM node:20.11-alpine as prod 

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

ENV NODE_ENV=production

EXPOSE 3000

WORKDIR /usr/src/app 

COPY nuxt.config.ts ./
COPY --from=build /usr/src/app/.nuxt ./.nuxt
COPY --from=build /usr/src/app/package*.json ./
COPY --from=build /usr/src/app/.output/ ./.output/ 
COPY --from=build /usr/src/app/prisma ./prisma 

CMD ["node", ".output/server/index.mjs"]

